### ISSUE TITLE
Rules for extending RPP

### ISSUE THREAD

**Issue by mario-loffredo** [SIDN/ietf-wg-rpp-charter#47]
What is missing in my opinion in both the "Extensibility" section of the requirements and the "Deliverables" section of the charter is the definition of rules for extending RPP.
On one hand, the rule for extending EPP is unique for requests and responses.
On the other hand, RPP allows to use different HTTP components to convey the protocol information between clients and servers (i.e. path segments, query parameters, request/response headers, request/response body), consequently, it is reasonable to expect that extensions will make use of all of them.
Shall implementers defining RPP extensions be guided to use one component rather than another based on some rules or will they be completely free to make their own choices?
I would prefer the first option. 
Following this, the mapping/conversion of EPP extensions into RPP counterparts should be done consistently with those rules.

**Comment by pawel-kow** [comment]
> What is missing in my opinion in both the "Extensibility" section of the requirements and the "Deliverables" section of the charter is the definition of rules for extending RPP. 

Hi Mario, absolutely.
Isn't it what requirements and later architecture would deal with?
Kind regards,
Pawel

**Comment by mario-loffredo** [comment]
Wouldn't make a comparison with EPP but it comes naturally to me.
The EPP core architecture is described in RFC5730 and this document includes a section titled "Protocol Extension Framework".
I think that the document describing the RPP core architecture should include a similar section.
Anyway, it makes more sense to me to address the RPP extension framework before dealing with any EPP-to-RPP mapping.

**Comment by mwullink** [comment]
A extension mechanism or framework is going to be an important part of RPP, the current concept charter states that this is in scope. It could be the case that future wg documents include a "Protocol Extension Framework" but i don't think that this needs to be explicitly mentioned in the charter.

I agree with Pawel, that the requirements and architecture for extensions are part of the work that needs to be done by the wg, and the charter reflects this.

**Comment by rpp-ietf** [comment]
We should certainly take what has worked with EPP in defining the extension points explicitly.  Define the base set of features with the pre-defined set of extension points (e.g., object, attribute, operation) and then define all the concrete objects as extensions.  We are reverse engineering the RDAP extension points now, which is not the path that I would recommend with RPP.   A provisioning protocol requires much more rigor than a lookup protocol like RDAP to ensure that what is persisted matches the client’s intent.

--

JG

***@***.***

James Gould
Fellow Engineer
***@***.******@***.***>

703-948-3271
12061 Bluemont Way
Reston, VA 20190

Verisign.com<http://verisigninc.com/>

From: Mario Loffredo ***@***.***>
Reply-To: SIDN/ietf-wg-rpp-charter ***@***.***>
Date: Tuesday, November 26, 2024 at 3:38 AM
To: SIDN/ietf-wg-rpp-charter ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [rpp] [SIDN/ietf-wg-rpp-charter] Rules for extending RPP (Issue #47)


Caution: This email originated from outside the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


What is missing in my opinion in both the "Extensibility" section of the requirements and the "Deliverables" section of the charter is the definition of rules for extending RPP.
On one hand, the rule for extending EPP is unique for requests and responses.
On the other hand, RPP allows to use different HTTP components to convey the protocol information between clients and servers (i.e. path segments, query parameters, request/response headers, request/response body), consequently, it is reasonable to expect that extensions will make use of all of them.
Shall implementers defining RPP extensions be guided to use one component rather than another based on some rules or will they be completely free to make their own choices?
I would prefer the first option.
Following this, the mapping/conversion of EPP extensions into RPP counterparts should be done consistently with those rules.

**Comment by mario-loffredo** [comment]
Most probably I misunderstood that defining an extension framework for RPP was taken for granted. SInce RPP aims to redesign EPP, I would have expected to see it as the first item in the list of the extensibility requirements. But never mind.
What matters is that there is a consensus about addressing this topic.

**Comment by jasdips** [comment]
The ongoing RDAP Extensions work should come handy for RPP extensions since RPP, like RDAP, would be HTTP and JSON based.

**Comment by pawel-kow** [comment]
> The ongoing RDAP Extensions work should come handy for RPP extensions since RPP, like RDAP, would be HTTP- and JSON-based.

Sure, there is also a lot of learning to take from RDAP.
This is still for me the work on requirements, architecture and finally on solutions.
Question remains: are we missing anything on the charter that would prevent the WG to proceed?

**Comment by mwullink** [comment]
i think extensions are covered well in the charter and we can close this issue now.
